{u'10': {u'active': True,
         u'address': [],
         u'comment': None,
         u'currentAccountBalance': -680.0,
         u'discountPercentage': None,
         u'email': None,
         u'fiscalNumber': None,
         u'hasCurrentAccount': True,
         u'id': 10,
         u'name': u'Lorenzo Rivero',
         u'paymentTypeId': None,
         u'phone': None},
 u'11': {u'active': True,
         u'address': [],
         u'comment': None,
         u'currentAccountBalance': 615.0,
         u'discountPercentage': None,
         u'email': u'carolina@lacicla.net',
         u'fiscalNumber': None,
         u'hasCurrentAccount': True,
         u'id': 11,
         u'name': u'La Cicla',
         u'paymentTypeId': 2,
         u'phone': None},
 u'12': {u'active': True,
         u'address': [],
         u'comment': None,
         u'currentAccountBalance': 450.0,
         u'discountPercentage': None,
         u'email': u'leandrosw@gmail.com',
         u'fiscalNumber': None,
         u'hasCurrentAccount': True,
         u'id': 12,
         u'name': u'Leandro Swietarski',
         u'paymentTypeId': None,
         u'phone': u'1540739511'},
 u'13': {u'active': True,
         u'address': [],
         u'comment': None,
         u'currentAccountBalance': 0.0,
         u'discountPercentage': None,
         u'email': u'jorge.roses@gmail.com',
         u'fiscalNumber': None,
         u'hasCurrentAccount': True,
         u'id': 13,
         u'name': u'Jorge Roses',
         u'paymentTypeId': 1,
         u'phone': u'+54 11 3098 1962'},
 u'2': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': -18.0,
        u'discountPercentage': None,
        u'email': u'gonzalo@origencowork.com',
        u'fiscalNumber': u'3333',
        u'hasCurrentAccount': True,
        u'id': 2,
        u'name': u'Gonzalo Parra',
        u'paymentTypeId': 2,
        u'phone': u'+54 9 11 2162 5416'},
 u'3': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': -20.0,
        u'discountPercentage': None,
        u'email': u'ler@origencowork.com',
        u'fiscalNumber': u'4444',
        u'hasCurrentAccount': True,
        u'id': 3,
        u'name': u'Lermit Rosell',
        u'paymentTypeId': 2,
        u'phone': u'+54 9 11 2398 9721\u202c'},
 u'4': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': 0.0,
        u'discountPercentage': None,
        u'email': u'chris@origencowork.com',
        u'fiscalNumber': u'2222',
        u'hasCurrentAccount': True,
        u'id': 4,
        u'name': u'Christian',
        u'paymentTypeId': 2,
        u'phone': u'+54 9 11 2688 0818\u202c'},
 u'5': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': -145.0,
        u'discountPercentage': None,
        u'email': u'dgo@origencowork.com',
        u'fiscalNumber': u'1111',
        u'hasCurrentAccount': True,
        u'id': 5,
        u'name': u'Diego Rosell',
        u'paymentTypeId': None,
        u'phone': u'\u202d+54 9 11 2393 8609\u202c'},
 u'6': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': -329.86,
        u'discountPercentage': None,
        u'email': u'lepadrong@gmail.com',
        u'fiscalNumber': None,
        u'hasCurrentAccount': True,
        u'id': 6,
        u'name': u'Luis Padron',
        u'paymentTypeId': 2,
        u'phone': u'+54 911 3059 7044'},
 u'7': {u'active': True,
        u'address': [u''],
        u'comment': None,
        u'currentAccountBalance': 0.0,
        u'discountPercentage': None,
        u'email': u'mblanco1329@gmail.com',
        u'fiscalNumber': u'0003',
        u'hasCurrentAccount': True,
        u'id': 7,
        u'name': u'Miriam Blanco',
        u'paymentTypeId': 1,
        u'phone': u'+54 11 2896 1869'},
 u'8': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': 0.0,
        u'discountPercentage': None,
        u'email': u'juanc.colmenares@gmail.com',
        u'fiscalNumber': u'0002',
        u'hasCurrentAccount': True,
        u'id': 8,
        u'name': u'Juan Carlos Colmenares',
        u'paymentTypeId': 1,
        u'phone': u'+54 11 3247 7127'},
 u'9': {u'active': True,
        u'address': [],
        u'comment': None,
        u'currentAccountBalance': 0.0,
        u'discountPercentage': None,
        u'email': u'barbisala@gmail.com',
        u'fiscalNumber': u'0001',
        u'hasCurrentAccount': True,
        u'id': 9,
        u'name': u'B\xe1rbara Salada',
        u'paymentTypeId': 1,
        u'phone': u'+54 155 420 4806'}}



{u'canceledAdditions': {u'amount': u'115.0', u'count': u'2.0'},
         u'payments': [{u'amount': u'330.0', u'paymentTypeId': 2}],
         u'people': None,
         u'rooms': [{u'amount': u'330.0', u'id': None}],
         u'salesCount': 1,
         u'totalTips': 0.0,
         u'totalTipsV1': 0,
         u'totals': [{u'amount': u'330.0', u'saleTypeId': 4}]}
